 
name: DepthAI ROS CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - humble
      - galactic
      - foxy
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - humble
      - galactic
      - foxy

jobs:

  linting:
    name: ament_${{ matrix.linter }} ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        linter: [clang_format, cpplint, xmllint, pep257, lint_cmake]
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: ros-tooling/setup-ros@0.3.2
    - uses: ros-tooling/action-ros2-lint@0.0.6
      with:
        distribution: humble
        linter: ${{ matrix.linter }}
        package-name: |
          depthai_bridge
          depthai_examples
          depthai_ros_msgs
          depthai_ros

  docker-build:
    name: Build and Upload to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        ROS_DISTRO: [humble]
    env: 
      PUSH: ${{ (github.event_name != 'pull_request') && (github.repository == 'luxonis/depthai-ros') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: env.PUSH == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            ROS_DISTRO=${{ matrix.ROS_DISTRO }}
            USE_RVIZ=1
          platforms: |
            amd64
            arm64
          push: ${{ env.PUSH }}
          no-cache: true
          tags: luxonis/depthai-ros:${{ matrix.ROS_DISTRO }}
